#!/usr/bin/env python3
"""Standard-library client: python3 examples/client.py AUDIO [AUDIO ...]."""
import argparse
import json
import mimetypes
import os
import sys
import time
import urllib.error
import urllib.request
import uuid
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("audio", type=Path, nargs="+", help="Multiple files require gateway mode")
    parser.add_argument("--url", default=os.getenv("ASR_BASE_URL", "http://127.0.0.1:8000"))
    parser.add_argument("--format", choices=["json", "verbose_json"], default="json")
    parser.add_argument("--uttid", action="append",
                        help="Gateway audio ID; repeat once per input file (otherwise generated by server)")
    parser.add_argument("--audio-format", choices=["pcm", "wav"],
                        help="Gateway input format (default: wav); pcm means 16 kHz mono PCM16LE")
    parser.add_argument("--timeout", type=float, default=7200)
    args = parser.parse_args()
    if args.uttid is not None and (len(args.uttid) != len(args.audio)
                                  or any(not value.strip() for value in args.uttid)
                                  or len(set(args.uttid)) != len(args.uttid)):
        parser.error("Provide one non-empty, unique --uttid per input file")
    boundary = uuid.uuid4().hex
    body = bytearray()
    fields = {"model": "fireredasr2-llm", "response_format": args.format,
              "temperature": "0", "repetition_penalty": "1.0",
              "max_completion_tokens": "512"}
    if args.audio_format:
        fields["audio_format"] = args.audio_format
    for key, value in fields.items():
        body.extend(f'--{boundary}\r\nContent-Disposition: form-data; name="{key}"\r\n\r\n{value}\r\n'.encode())
    for value in args.uttid or []:
        body.extend(f'--{boundary}\r\nContent-Disposition: form-data; name="uttid"\r\n\r\n{value}\r\n'.encode())
    for audio in args.audio:
        media = mimetypes.guess_type(audio.name)[0] or "application/octet-stream"
        filename = audio.name.replace("\r", "%0D").replace("\n", "%0A").replace('"', "%22").replace("\\", "%5C")
        body.extend(f'--{boundary}\r\nContent-Disposition: form-data; name="file"; filename="{filename}"\r\nContent-Type: {media}\r\n\r\n'.encode())
        body.extend(audio.read_bytes())
        body.extend(b"\r\n")
    body.extend(f"--{boundary}--\r\n".encode())
    headers = {"Content-Type": f"multipart/form-data; boundary={boundary}"}
    key = os.getenv("ASR_API_KEY")
    if key:
        headers["Authorization"] = f"Bearer {key}"
    request = urllib.request.Request(args.url.rstrip("/") + "/v1/audio/transcriptions",
                                     data=bytes(body), headers=headers)
    started = time.monotonic()
    try:
        with urllib.request.urlopen(request, timeout=args.timeout) as response:
            result = response.read().decode()
    except urllib.error.HTTPError as exc:
        print(f"HTTP {exc.code}: {exc.read().decode()}", file=sys.stderr)
        raise SystemExit(1)
    decoded = json.loads(result)
    errors = decoded.get("errors", [])
    result = json.dumps(decoded, ensure_ascii=False, indent=2)
    print(result)
    print(f"Elapsed: {time.monotonic() - started:.2f}s", file=sys.stderr)
    if errors:
        print(f"{len(errors)} file(s) failed; see errors in the response.", file=sys.stderr)
        raise SystemExit(1)


if __name__ == "__main__":
    main()
